[package]
name = "rnmrfit"
version = "0.1.0"
authors = ["Stanislav Sokolenko <stanislav@sokolenko.net>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "*"
ndarray = "0.13.0"
rustnmrfit = { path = "../rustnmrfit", version = "0.1.0" }
