# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @importFrom Rcpp sourceCpp
#' @import nloptr
#' @useDynLib rnmrfit
NULL

#' @export
fit_lineshape_1d <- function(x_val, y_val, par, lb, ub, basis_val, eq, ineq, n_peaks, n_baseline, n_phase) {
    .Call('_rnmrfit_fit_lineshape_1d', PACKAGE = 'rnmrfit', x_val, y_val, par, lb, ub, basis_val, eq, ineq, n_peaks, n_baseline, n_phase)
}

lineshape_1d <- function(x_direct, y, par) {
    invisible(.Call('_rnmrfit_lineshape_1d', PACKAGE = 'rnmrfit', x_direct, y, par))
}

